name: tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-test:
    strategy:
      matrix:
        go: [ 1.19 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v3
      - name: Install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32  # v4
        with:
          go-version: ${{ matrix.go }}
      - name: Prepare external plugin tests
        run: |
          go build -buildmode=plugin -o tests/yor_plugins/example/extra_tags.so tests/yor_plugins/example/*.go
          go build -buildmode=plugin -o tests/yor_plugins/tag_group_example/extra_tag_groups.so tests/yor_plugins/tag_group_example/*.go
      - name: Test
        run: go build -v && go test ./src/...
  linter:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@7708105983c614f7a2725e2172908b7709d1c3e4  # v2
        with:
          tool_name: golangci-lint
          fail_on_error: true
          golangci_lint_flags: "--skip-dirs tests/yor_plugins"
  integration-tests:
    strategy:
      matrix:
        go: [ 1.19 ]
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v3
      - name: Install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32  # v4
        with:
          go-version: ${{ matrix.go }}
      - name: build
        run: go build
      - name: Clone Terragoat - vulnerable terraform
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v3
        with:
          repository: bridgecrewio/terragoat  # clone https://github.com/bridgecrewio/terragoat/
          fetch-depth: 0
          clean: false
          path: 'terragoat'
          ref: 063dc2db3bb036160ed39d3705508ee8293a27c8
      - name: Run yor
        run: |
          git config --local user.email "action@github.com"
          ./yor list-tags -g code2cloud,git > list-tags-result.txt
          ./yor tag -d terragoat -o json --output-json-file result.json
      - name: Run integration tests
        run: go test -race ./tests/integration/...
